### ISSUE TITLE
Could you fix dependencies?

### ISSUE THREAD

**Issue by henry090** [egenn/rtemis#6]
```
mod <- elevate(iris)
[2019-05-15 20:35:47 elevate] Hello, turgut
[2019-05-15 20:35:48 depCheck] Dependencies missing:
     pbapply

Error in elevate(iris) : Please install dependencies and try again
```

```
epCheck] Dependencies missing:
     ranger

Error in s.RANGER(x = list(Sepal.Length = c(4.7, 4.6, 5, 5.4, 5, 4.4,  : 
  Please install dependencies and try again

```

**Comment by egenn** [comment]
> ```
> mod <- elevate(iris)
> [2019-05-15 20:35:47 elevate] Hello, turgut
> [2019-05-15 20:35:48 depCheck] Dependencies missing:
>      pbapply
> 
> Error in elevate(iris) : Please install dependencies and try again
> ```
> 
> 
> ```
> epCheck] Dependencies missing:
>      ranger
> 
> Error in s.RANGER(x = list(Sepal.Length = c(4.7, 4.6, 5, 5.4, 5, 4.4,  : 
>   Please install dependencies and try again
> ```

Hi

**pbapply** and **ranger** are both listed under Suggests in the DESCRIPTION file.
`depCheck` is working as expected and telling you they are not available on your system - you can install them using `install.packages()`

You could install all dependencies listed in Suggests by passing `dependencies = TRUE` to `remotes::install_github`, but I don't recommend that because it's a long list and most users would only use a subset of those.

I have updated the Readme file to make sure the minimum requirements for running the example are installed.
